apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdd
  namespace: cours-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:15.8-bookworm
          env:
            - name: POSTGRES_DB
              value: "cours1"
            - name: POSTGRES_USER
              value: "cours1"
            - name: POSTGRES_PASSWORD
              value: "cours1"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-volume
            - mountPath: /etc/localtime
              name: localtime
              readOnly: true
      volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: db-pvc
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: File
