apiVersion: v1
kind: Service
metadata:
  name: bdd-service
  namespace: cours-app
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432
  type: NodePort
